---
- hosts: 172.31.94.241
  become: yes
  tasks:
   - name: i wnat to install git
     yum:
      name: git
      state: present

   - name: i wnat to install tree
     yum:
      name: tree
      stateeee: present
     ignore_errors: yes

   - name: i wnat to install wget
     yum:
      name: wget
      state: present