---
- hosts: all
  become: yes
  tasks:
  - name: i want to install git, tree and wget by using single task
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - git
      - wget
      - tree