---
- hosts: all
  become: yes
  tasks:
  - name: i want to install git, tree and wget by using single tasks
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - git
      - tree
      - wget
  