---
- hosts: 172.31.94.241
  become: yes
  tasks:
   - name: i wnat to install git
     apt:
      name: git
      state: present
     tags: mygit

   - name: i wnat to install tree
     apt:
      name: tree
      state: present
     tags: mytree

   - name: i wnat to install wget
     apt:
      name: wget
      state: present
     tags: mywget