---
- hosts: all
  become: yes
  tasks:
  - name: install web server only on RedHat nodes
    yum:
     name: httpd
     state: present
    when: ansible_os_family=="RedHat"

  - name: start web server only on RedHat nodes
    service:
     name: httpd
     state: started
    when: ansible_os_family=="RedHat"
