---
- hosts: all
  become: yes
  tasks:
  - name: install web server only on ubuntu server
    apt:
     name: apache2
     state: present
    when: ansible_os_family=="Debian"
    
  - name: start web server only on ubuntu server
    service:
     name: apache2
     state: started
    when: ansible_os_family=="Debian"
